# NOTE: We should not change the Desc-ID mapping at any time.
rejectReason:
  - desc: "亲，您的资料填写不规范，请重新填写"
    id: "1"
  - desc: "亲，您的资料照片不符规范，请重新拍照上传"
    id: "2"
  - desc: "亲，您的申请未通过系统审核，抱歉"
    id: "3"
  - desc: "亲，您暂时不符合申请条件"
    id: "4"
  - desc: "您近期有不通过记录，请一个月后再申请"
    id: "5"
  - desc: "您的综合情况欠佳，不符合申请要求"
    id: "6"
  - desc: "您未满18岁，不符合申请要求"
    id: "7"
  - desc: "您的信用记录存在瑕疵，不符合申请要求"
    id: "8"
  - desc: "您在'我来贷'的历史记录不佳，不符合申请要求"
    id: "9"
  - desc: "您在'我来贷'的借款正在逾期，请结清后再申请"
    id: "10"
  - desc: "您在'我来贷'的信用额度不足"
    id: "11"
  - desc: "经过我们的评估，您的综合情况暂不符合“我来贷”的申请条件，请您一个月后再提交申请"
    id: "12"
  - desc: "抱歉，你所在的地区暂时不在“我来贷”的服务范围内。"
    id: "13"
  - desc: "抱歉，你所在的学校暂时不在“我来贷”的服务范围内。"
    id: "14"
  - desc: "抱歉，目前“我来贷”只向在校大学生提供贷款服务。"
    id: "15"