# NOTE: We should not change the Desc-ID mapping at any time.
pushbackReason:
  - desc: "您的资料照片过于模糊，请重新拍照上传"
    id: "1"
  - desc: "您的资料照片不完整，请对照要求补充拍照上传"
    id: "2"
  - desc: "您的资料照片不符合规范，请重新拍照上传"
    id: "3"
  - desc: "您的信息填写不完整，请补充详细信息后重新提交"
    id: "4"
  - desc: "您的电话多次未能接通，请重新提交申请"
    id: "5"
